using OuterloopLabApi.Models;
using OuterloopLabApi.RateProviders;
using OuterloopLabApi.Repositories;

namespace OuterloopLabApi.Services;

public sealed class CurrencyConversionService
{
    private readonly ICurrencyRateProvider _rateProvider;
    private readonly IAuditRepository _auditRepository;

    public CurrencyConversionService(ICurrencyRateProvider rateProvider, IAuditRepository auditRepository)
    {
        _rateProvider = rateProvider;
        _auditRepository = auditRepository;
    }

    public async Task<ConversionResponse> ConvertAsync(ConversionRequest request, CancellationToken cancellationToken)
    {
        var from = request.FromCurrency.Trim().ToUpperInvariant();
        var to = request.ToCurrency.Trim().ToUpperInvariant();
        var amount = request.Amount;

        var exchangeRate = await _rateProvider.GetRateAsync(from, to, cancellationToken);
        var converted = amount * exchangeRate.Rate;

        // Constraint: authoritative execution timestamp is generated by the backend.
        var executionTimestampUtc = DateTime.UtcNow;
        var auditId = Guid.NewGuid().ToString();

        var record = new AuditRecord
        {
            Id = auditId,
            AuditId = auditId,
            FromCurrency = from,
            ToCurrency = to,
            Amount = amount,
            ExchangeRate = exchangeRate.Rate,
            ConvertedAmount = converted,
            ProviderDateMarker = exchangeRate.ProviderDateMarker,
            ExecutionTimestampUtc = executionTimestampUtc
        };

        await _auditRepository.AddAsync(record, cancellationToken);

        return new ConversionResponse
        {
            AuditId = auditId,
            FromCurrency = from,
            ToCurrency = to,
            Amount = amount,
            ExchangeRate = exchangeRate.Rate,
            ConvertedAmount = converted,
            ProviderDateMarker = exchangeRate.ProviderDateMarker,
            ExecutionTimestampUtc = executionTimestampUtc
        };
    }
}
